'use client';
import {useState} from 'react';
const fixtures=[['Abubakar FC','Mowolowo FC','25 Aug 2026','12:00 PM','Home'],['Abubakar FC','Ajaawa United','30 Aug 2026','4:00 PM','Away']];
const results=[['Abubakar FC','Oke-Odo FC','3 - 1','Won'],['Igbogbo FC','Abubakar FC','2 - 2','Draw']];
const players=[['01','Olusanjo','Goalkeeper'],['15','Abubakar','Defender • Captain'],['05','Gbotemi','Defender'],['06','Sudiq','Midfielder'],['09','Boluwatife','Forward'],['11','Pepe','Forward']];
export default function Home(){const [tab,setTab]=useState('home'); const [admin,setAdmin]=useState(false); const nav=['home','fixtures','results','legends','achievements','players']; return <main>
<header><div className="brand"><div className="crest">AF</div><div><b>ABUBAKAR FC</b><span>Raising unknown talent into unstoppable football stars.</span></div></div><nav>{nav.map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x[0].toUpperCase()+x.slice(1)}</button>)}href="/admin">Administrator</a></nav></header>
{tab==='home'&&<section className="hero"><div><p className="eyebrow">WELCOME TO THE OFFICIAL CLUB SITE</p><h1>ABUBAKAR<br/><em>FOOTBALL CLUB</em></h1><p className="lead">Follow our fixtures, results, legends, achievements and players — all in one place.</p><div><button className="primary" onClick={()=>setTab('fixtures')}>View fixtures</button><button className="ghost" onClick={()=>setTab('players')}>Meet the squad</button></div></div><div className="heroCard"><span>UP NEXT</span><h3>Abubakar FC</h3><strong>VS</strong><h3>Mowolowo FC</h3><p>25 AUGUST 2026 • 12:00 PM</p></div></section>}
{tab==='fixtures'&&<Section title="Fixtures" items={fixtures.map(f=><Card title={`${f[0]} vs ${f[1]}`} meta={`${f[2]} • ${f[3]} • ${f[4]}`} />)}/>} 
{tab==='results'&&<Section title="Results" items={results.map(r=><Card title={`${r[0]} ${r[2]} ${r[1]}`} meta={r[3]}/>)} />}
{tab==='players'&&<section className="content"><h2>Players</h2><div className="grid">{players.map(p=><article className="player"><div className="number">{p[0]}</div><h3>{p[1]}</h3><p>{p[2]}</p></article>)}</div></section>}
{tab==='legends'&&<section className="content"><h2>Club Legends</h2><div className="legend"><div className="avatar">★</div><div><h3>The players who built the story</h3><p>This section is ready for your legendary players, photos, biographies and career statistics.</p></div></div></section>}
{tab==='achievements'&&<section className="content"><h2>Achievements</h2><div className="grid"><Card title="Club Honours" meta="Add trophies, tournament wins and milestones here."/><Card title="2026 Campaign" meta="Track the season record and major moments."/></div></section>}
<footer><b>ABUBAKAR FC</b><span>Official club website • © 2026</span></footer>
{admin&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>setAdmin(false)}>×</button><h2>Administrator</h2><p>Admin access is ready for connection to your secure account.</p><label>Email<input placeholder="admin@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="primary full" onClick={()=>alert('Admin authentication will be connected next.')}>Log in</button></div></div>}
</main>}
function Section({title,items}){return <section className="content"><h2>{title}</h2><div className="grid">{items}</div></section>}; function Card({title,meta}){return <article className="card"><h3>{title}</h3><p>{meta}</p></article>}
